export const batches = [
  {
    code: "IGNITE-2025-A",
    name: "Full Stack Batch January 2025",
    domain: "Full Stack",
    startDate: "Jan 15, 2025",
    endDate: "May 10, 2025",
    status: "Upcoming",
    trainees: 30,
  },
  {
    code: "IGNITE-2024-B",
    name: "Java Development Batch December",
    domain: "Java",
    startDate: "Dec 01, 2024",
    endDate: "Apr 01, 2025",
    status: "Ongoing",
    trainees: 28,
  },
  {
    code: "IGNITE-2024-A",
    name: "AI / ML Advanced Track",
    domain: "AI / ML",
    startDate: "Oct 15, 2024",
    endDate: "Feb 15, 2025",
    status: "Ongoing",
    trainees: 25,
  },
  {
    code: "IGNITE-2023-D",
    name: "Cloud Computing Batch",
    domain: "Cloud",
    startDate: "Sep 01, 2023",
    endDate: "Dec 31, 2023",
    status: "Completed",
    trainees: 29,
  },
  {
    code: "IGNITE-2023-C",
    name: "Data Engineering Track",
    domain: "Data Engineering",
    startDate: "Jul 15, 2023",
    endDate: "Nov 15, 2023",
    status: "Archived",
    trainees: 27,
  },
  {
    code: "IGNITE-2023-B",
    name: "Java Full Stack Accelerated",
    domain: "Full Stack",
    startDate: "Jun 01, 2023",
    endDate: "Oct 01, 2023",
    status: "Completed",
    trainees: 29,
  },
  {
    code: "IGNITE-2023-A",
    name: "Python & Automation Track",
    domain: "Automation",
    startDate: "Apr 10, 2023",
    endDate: "Aug 10, 2023",
    status: "Archived",
    trainees: 24,
  },
];
