import { TbCsv } from "react-icons/tb";

export const TEAM_DATA = [
  {
    id: 1,
    name: "Justin Bieber",
    role: "Manager",
    email: "justin.bieber@tcs.com",
    tasksDone: 42,
    hoursLogged: "156h",
    status: "Active",
    team: true,
    phone: +918778306729,
    img: "https://randomuser.me/api/portraits/men/31.jpg",
  },
  {
    id: 2,
    name: "Sophia Williams",
    role: "Developer",
    email: "sophia.williams@tcs.com",
    tasksDone: 58,
    hoursLogged: "210h",
    status: "Busy",
    team: true,
    phone: +918778306729,
    img: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    id: 3,
    name: "Michael Davis",
    role: "Tester",
    email: "michael.davis@tcs.com",
    tasksDone: 33,
    hoursLogged: "98h",
    status: "Idle",
    team: true,
    phone: +918778306729,
    img: "https://randomuser.me/api/portraits/men/76.jpg",
  },
  {
    id: 4,
    name: "Emma Thompson",
    role: "Senior Developer",
    email: "emma.thompson@tcs.com",
    tasksDone: 50,
    hoursLogged: "190h",
    status: "Active",
    team: true,
    phone: +918778306729,
    img: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 5,
    name: "Daniel Carter",
    role: "Business Analyst",
    email: "daniel.carter@tcs.com",
    tasksDone: 21,
    hoursLogged: "65h",
    status: "Offline",
    team: true,
    phone: +918778306729,

    img: "https://randomuser.me/api/portraits/men/84.jpg",
  },
  {
    id: 6,
    name: "Olivia Brown",
    role: "UI/UX Designer",
    email: "olivia.brown@tcs.com",
    tasksDone: 47,
    hoursLogged: "172h",
    status: "Active",
    team: true,
    phone: +918778306729,

    img: "https://randomuser.me/api/portraits/women/68.jpg",
  },
  {
    id: 7,
    name: "Aiden Smith",
    role: "Project Lead",
    email: "aiden.smith@tcs.com",
    tasksDone: 66,
    hoursLogged: "243h",
    status: "Busy",
    team: true,
    phone: +918778306729,

    img: "https://randomuser.me/api/portraits/men/53.jpg",
  },
  {
    id: 8,
    name: "Chloe Martin",
    role: "HR Coordinator",
    email: "chloe.martin@tcs.com",
    tasksDone: 14,
    hoursLogged: "40h",
    status: "Active",
    team: true,
    phone: +918778306729,

    img: "https://randomuser.me/api/portraits/women/75.jpg",
  },
  {
    id: 9,
    name: "Ethan Walker",
    role: "QA Lead",
    email: "ethan.walker@tcs.com",
    tasksDone: 39,
    hoursLogged: "134h",
    status: "Idle",
    team: true,
    phone: +918778306729,

    img: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    id: 10,
    name: "Grace Hall",
    role: "Scrum Master",
    email: "grace.hall@tcs.com",
    tasksDone: 55,
    hoursLogged: "185h",
    status: "Active",
    team: true,
    phone: +918778306729,

    img: "https://randomuser.me/api/portraits/women/27.jpg",
  },
  {
    id: 11,
    name: "Logan White",
    role: "DevOps Engineer",
    email: "logan.white@tcs.com",
    tasksDone: 62,
    hoursLogged: "225h",
    status: "Active",
    team: false,
    phone: +918778306729,

    img: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 12,
    name: "Isabella Perez",
    role: "Technical Architect",
    email: "isabella.perez@tcs.com",
    tasksDone: 88,
    hoursLogged: "310h",
    status: "Busy",
    team: false,
    phone: +918778306729,

    img: "https://randomuser.me/api/portraits/women/53.jpg",
  },
  {
    id: 13,
    name: "Lucas Anderson",
    role: "Full Stack Developer",
    email: "lucas.anderson@tcs.com",
    tasksDone: 72,
    hoursLogged: "260h",
    status: "Active",
    team: false,
    phone: +918778306729,

    img: "https://randomuser.me/api/portraits/men/25.jpg",
  },
  {
    id: 14,
    name: "Mia Johnson",
    role: "Support Engineer",
    email: "mia.johnson@tcs.com",
    tasksDone: 27,
    hoursLogged: "90h",
    status: "Idle",
    team: false,
    phone: +918778306729,
    img: "https://randomuser.me/api/portraits/women/42.jpg",
  },
  {
    id: 15,
    name: "Benjamin Lee",
    role: "Cloud Engineer",
    email: "benjamin.lee@tcs.com",
    tasksDone: 49,
    hoursLogged: "160h",
    status: "Offline",
    team: false,
    phone: +918778306729,
    img: "https://randomuser.me/api/portraits/men/66.jpg",
  },
  {
    id: 16,
    name: "Harper Robinson",
    role: "Product Manager",
    email: "harper.robinson@tcs.com",
    tasksDone: 37,
    hoursLogged: "120h",
    status: "Active",
    team: false,
    phone: +918778306729,
    img: "https://randomuser.me/api/portraits/women/20.jpg",
  },
  {
    id: 17,
    name: "Nathan King",
    role: "Security Analyst",
    email: "nathan.king@tcs.com",
    tasksDone: 61,
    hoursLogged: "198h",
    status: "Busy",
    team: false,
    phone: +918778306729,
    email: "adithiyan.r@TbCsv.com",
    img: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: 18,
    name: "Ava Scott",
    role: "Frontend Developer",
    email: "ava.scott@tcs.com",
    tasksDone: 44,
    hoursLogged: "150h",
    status: "Busy",
    team: false,
    phone: +918778306729,
    img: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    id: 19,
    name: "Elijah Baker",
    role: "Software Engineer",
    email: "elijah.baker@tcs.com",
    tasksDone: 53,
    hoursLogged: "175h",
    status: "Active",
    phone: +918778306729,
    img: "https://randomuser.me/api/portraits/men/40.jpg",
  },
  {
    id: 20,
    name: "Lily Parker",
    role: "Data Analyst",
    email: "lily.parker@tcs.com",
    tasksDone: 29,
    hoursLogged: "102h",
    status: "Active",
    team: false,
    phone: +918778306729,
    img: "https://randomuser.me/api/portraits/women/10.jpg",
  },
];
