export const users = [
  {
    id: "TCS001",
    name: "John Doe",
    email: "john.doe@tcs.com",
    role: "Developer",
    team: "Development",
    status: "Active",
  },
  {
    id: "TCS002",
    name: "Priya Sharma",
    email: "priya.sharma@tcs.com",
    role: "Manager",
    team: "Development",
    status: "Active",
  },
  {
    id: "TCS003",
    name: "Rahul Verma",
    email: "rahul.verma@tcs.com",
    role: "TA",
    team: "Quality Assurance",
    status: "Active",
  },
  {
    id: "TCS004",
    name: "Sneha Patel",
    email: "sneha.patel@tcs.com",
    role: "Developer",
    team: "Development",
    status: "Inactive",
  },
  {
    id: "TCS005",
    name: "Amit Kumar",
    email: "amit.kumar@tcs.com",
    role: "Senior / SME",
    team: "Architecture",
    status: "Active",
  },

  {
    id: "TCS006",
    name: "Rohit Mehta",
    email: "rohit.mehta@tcs.com",
    role: "Developer",
    team: "Development",
    status: "Active",
  },
  {
    id: "TCS007",
    name: "Anjali Iyer",
    email: "anjali.iyer@tcs.com",
    role: "TA",
    team: "Quality Assurance",
    status: "Active",
  },
  {
    id: "TCS008",
    name: "Karthik R",
    email: "karthik.r@tcs.com",
    role: "Developer",
    team: "Development",
    status: "Active",
  },
  {
    id: "TCS009",
    name: "Neha Singh",
    email: "neha.singh@tcs.com",
    role: "Manager",
    team: "Operations",
    status: "Active",
  },
  {
    id: "TCS010",
    name: "Vikram Joshi",
    email: "vikram.joshi@tcs.com",
    role: "Senior / SME",
    team: "Architecture",
    status: "Active",
  },

  {
    id: "TCS011",
    name: "Pooja Nair",
    email: "pooja.nair@tcs.com",
    role: "Developer",
    team: "Development",
    status: "Inactive",
  },
  {
    id: "TCS012",
    name: "Arjun Malhotra",
    email: "arjun.m@tcs.com",
    role: "TA",
    team: "Quality Assurance",
    status: "Active",
  },
  {
    id: "TCS013",
    name: "Divya Rao",
    email: "divya.rao@tcs.com",
    role: "Manager",
    team: "HR Systems",
    status: "Active",
  },
  {
    id: "TCS014",
    name: "Suresh Babu",
    email: "suresh.babu@tcs.com",
    role: "Developer",
    team: "Development",
    status: "Active",
  },
  {
    id: "TCS015",
    name: "Meera Menon",
    email: "meera.menon@tcs.com",
    role: "Senior / SME",
    team: "Architecture",
    status: "Active",
  },

  {
    id: "TCS016",
    name: "Nikhil Jain",
    email: "nikhil.jain@tcs.com",
    role: "Developer",
    team: "Development",
    status: "Active",
  },
  {
    id: "TCS017",
    name: "Shalini Gupta",
    email: "shalini.gupta@tcs.com",
    role: "TA",
    team: "Quality Assurance",
    status: "Inactive",
  },
  {
    id: "TCS018",
    name: "Manoj Kumar",
    email: "manoj.kumar@tcs.com",
    role: "Manager",
    team: "Operations",
    status: "Active",
  },
  {
    id: "TCS019",
    name: "Aishwarya S",
    email: "aishwarya.s@tcs.com",
    role: "Developer",
    team: "Development",
    status: "Active",
  },
  {
    id: "TCS020",
    name: "Ramesh Iyer",
    email: "ramesh.iyer@tcs.com",
    role: "Senior / SME",
    team: "Architecture",
    status: "Active",
  },

  {
    id: "TCS021",
    name: "Harish K",
    email: "harish.k@tcs.com",
    role: "Developer",
    team: "Development",
    status: "Inactive",
  },
  {
    id: "TCS022",
    name: "Lavanya R",
    email: "lavanya.r@tcs.com",
    role: "TA",
    team: "Quality Assurance",
    status: "Active",
  },
  {
    id: "TCS023",
    name: "Sanjay Mishra",
    email: "sanjay.mishra@tcs.com",
    role: "Manager",
    team: "Delivery",
    status: "Active",
  },
  {
    id: "TCS024",
    name: "Keerthi S",
    email: "keerthi.s@tcs.com",
    role: "Developer",
    team: "Development",
    status: "Active",
  },
  {
    id: "TCS025",
    name: "Balaji N",
    email: "balaji.n@tcs.com",
    role: "Senior / SME",
    team: "Architecture",
    status: "Inactive",
  },

  {
    id: "TCS026",
    name: "Anand P",
    email: "anand.p@tcs.com",
    role: "Developer",
    team: "Development",
    status: "Active",
  },
  {
    id: "TCS027",
    name: "Swetha K",
    email: "swetha.k@tcs.com",
    role: "TA",
    team: "Quality Assurance",
    status: "Active",
  },
  {
    id: "TCS028",
    name: "Prakash R",
    email: "prakash.r@tcs.com",
    role: "Manager",
    team: "Operations",
    status: "Active",
  },
  {
    id: "TCS029",
    name: "Kiran S",
    email: "kiran.s@tcs.com",
    role: "Developer",
    team: "Development",
    status: "Active",
  },
  {
    id: "TCS030",
    name: "Sathish V",
    email: "sathish.v@tcs.com",
    role: "Senior / SME",
    team: "Architecture",
    status: "Active",
  },

  {
    id: "TCS031",
    name: "Nandhini M",
    email: "nandhini.m@tcs.com",
    role: "Developer",
    team: "Development",
    status: "Active",
  },
  {
    id: "TCS032",
    name: "Kunal Shah",
    email: "kunal.shah@tcs.com",
    role: "TA",
    team: "Quality Assurance",
    status: "Inactive",
  },
  {
    id: "TCS033",
    name: "Ritu Agarwal",
    email: "ritu.agarwal@tcs.com",
    role: "Manager",
    team: "HR Systems",
    status: "Active",
  },
  {
    id: "TCS034",
    name: "Deepak S",
    email: "deepak.s@tcs.com",
    role: "Developer",
    team: "Development",
    status: "Active",
  },
  {
    id: "TCS035",
    name: "Mohan Raj",
    email: "mohan.raj@tcs.com",
    role: "Senior / SME",
    team: "Architecture",
    status: "Active",
  },

  {
    id: "TCS036",
    name: "Pavithra R",
    email: "pavithra.r@tcs.com",
    role: "Developer",
    team: "Development",
    status: "Inactive",
  },
  {
    id: "TCS037",
    name: "Siddharth K",
    email: "siddharth.k@tcs.com",
    role: "TA",
    team: "Quality Assurance",
    status: "Active",
  },
  {
    id: "TCS038",
    name: "Anitha S",
    email: "anitha.s@tcs.com",
    role: "Manager",
    team: "Delivery",
    status: "Active",
  },
  {
    id: "TCS039",
    name: "Vignesh R",
    email: "vignesh.r@tcs.com",
    role: "Developer",
    team: "Development",
    status: "Active",
  },
  {
    id: "TCS040",
    name: "Krishna Mohan",
    email: "krishna.mohan@tcs.com",
    role: "Senior / SME",
    team: "Architecture",
    status: "Active",
  },
];
